### ISSUE TITLE
Deeper Transfer-Related Gas Reportings

### ISSUE THREAD

**Issue by johnnyshankman** [beskay/ERC721B#8]
The main drawback of ERC721A is its gas costs upon transfer. I'd like to see a deeper drill down into how this behaves in various transfer contexts to see if this has the same issues.

See:
https://twitter.com/CryptoMuppa/status/1496137580999548943?s=20&t=Vb0IDAmMLzIPCb7plnQuUA
https://twitter.com/MilkyTasteEth/status/1496577498192412672?s=20&t=Vb0IDAmMLzIPCb7plnQuUA
https://twitter.com/whalegoddess/status/1500985266185539591?s=20&t=Vb0IDAmMLzIPCb7plnQuUA

**Comment by beskay** [comment]
Yes, you are correct, in the end you dont save gas fees when using ERC721A compared to OpenZeppelin's standard ERC721 contracts. The gas fees you save during mint will be added in subsequent transfers. The same happens here, although there are less storage writes compared to ERC721A, so ERC721B transfers are in general a bit cheaper than ERC721A transfers.

ERC721B transfers are also cheaper than ERC721Enumerable transfers, but they are NOT cheaper than standard ERC721 transfers. The main advantage is really just the cheap mint. 

However, only the first transfer is more expensive, after that the fees are even cheaper than standard ERC721 transfers. I've added some extra tests in the "Gas analysis" describe block, if you want to test this yourself. 

Here are the results:
```
Gas used for first transfer: 75989
Gas used for second transfer: 37541

Gas used for first safeTransfer: 78828
Gas used for second safeTransfer: 40380
```

**Comment by johnnyshankman** [comment]
Very interesting! Thank you @beskay wonderful work here.

**Comment by beskay** [comment]
Thank you!
