### ISSUE TITLE
Missing Implementation

### ISSUE THREAD

**Issue by darkerego** [beskay/ERC721B#9]
Hi, the compiler is complaining that the tokenURI method is missing? Or am I missing something? If I add a function to get the tokenURI, it compiles fine.

**Comment by beskay** [comment]
Hi, yes, the tokenURI method is not implemented, this is the reason the contract is marked as `abstract contract`. Just implement it yourself (as you did) and everything is fine.

**Comment by darkerego** [comment]
Okay,  gotcha, thanks.
